### ISSUE TITLE
cf open with an https option

### ISSUE THREAD

**Issue by austinmcdaniel** [cloudfoundry-community/cf-plugin-open#15]
Our CF instance only allows https URL access so it would be really cool if this could open straight to the https url.

**Comment by drnic** [comment]
@austinmcdaniel sorry only just found this issue/discussion. Do you think it should just default to `https:` by default? https://github.com/cloudfoundry-community/cf-plugin-open/blob/master/open.go#L90 Sounds good to me.

If you're keen, perhaps throw in a PR.

**Comment by austinmcdaniel** [comment]
Yeah, https should be the most common protocol used.

**Comment by drnic** [comment]
This has been pushed out in v1.2.0 and available via `cf install-plugin open`
