### ISSUE TITLE
'Open' Plugin Questions

### ISSUE THREAD

**Issue by goehmen** [cloudfoundry-community/cf-plugin-open#2]
This plugin is great!  It reminded me that there are a couple similar stories in the CF CLI icebox that now might not have to be done!
- 'cf open' for linux/osx - https://www.pivotaltracker.com/story/show/70243070
- 'cf open' for windows - https://www.pivotaltracker.com/story/show/70305100

As I read those stories, I found a few interesting notes that could apply to your plugin.  

Curious to know:
- Is the plugin linux/osx specific or does it also work on windows?
- does the plugin try to open the first defined route for the app?  or how does it handle multiple routes?
- is there error handling if app has no routes defined?

**Comment by longnguyen11288** [comment]
Hi @goehmen 

Thanks! I've been wanting something like this for some time. With plugin support it make it a lot easier to write.
 
1) This should work on windows. I don't have window machine so I can't test it. 
2) Currently it just grabs first route. I will add in selection if there are more then 1 route. [Ticket](https://github.com/cloudfoundry-community/cf-cli-open/issues/3)
3) There isn't error handling for no routes defined. [Ticket](https://github.com/cloudfoundry-community/cf-cli-open/issues/4)

**Comment by longnguyen11288** [comment]
This is complete in v 1.1
